ALTER TABLE hops
    ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS hop_comments (
    id BIGSERIAL PRIMARY KEY,
    hop_id BIGINT NOT NULL REFERENCES hops(id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hop_images (
    id BIGSERIAL PRIMARY KEY,
    hop_id BIGINT NOT NULL REFERENCES hops(id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    content_type TEXT NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
